apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmp-portal
  namespace: cmp-portal-dev
  labels:
    app: cmp-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmp-portal
  template:
    metadata:
      labels:
        app: cmp-portal
    spec:
      containers:
        - name: cmp-portal
          image: docker.io/nmthanh31/cmp-portal:v3.6.0-test
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # env:
          #   - name: AMS_UPSTREAM
          #     value: "http://cmp-ams.cmp-backend-dev.svc.cluster.local:8080"
          #   - name: BILLING_UPSTREAM
          #     value: "http://cmp-billing.cmp-backend-dev.svc.cluster.local:8080"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
