apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-backend-config
  namespace: cmp-backend-dev
data:
  CMP_AMS_BILLING_GRPC_ADDRESS: "static://cmp-billing:9091"
  CMP_AMS_BILLING_GRPC_DEADLINE_MS: "3000"
  CMP_AMS_CACHE_CONNECT_TIMEOUT: "3s"
  CMP_AMS_CACHE_HOST: "10.0.0.51"
  CMP_AMS_CACHE_PORT: "6379"
  CMP_AMS_CACHE_TIMEOUT: "5s"
  CMP_AMS_CORS_ALLOW_CREDENTIALS: "true"
  CMP_AMS_CORS_ALLOWED_HEADERS: "*"
  CMP_AMS_CORS_ALLOWED_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD"
  CMP_AMS_CORS_ALLOWED_ORIGIN_PATTERNS: "*"
  CMP_AMS_CORS_EXPOSED_HEADERS: "Authorization,Content-Type,X-Request-Id,Set-Cookie,X-XSRF-TOKEN"
  CMP_AMS_DB_HIKARI_CONNECTION_TIMEOUT: "3000"
  CMP_AMS_DB_HIKARI_MAXIMUM_POOL_SIZE: "20"
  CMP_AMS_DB_HIKARI_MINIMUM_IDLE: "5"
  CMP_AMS_DB_HIKARI_VALIDATION_TIMEOUT: "1000"
  CMP_AMS_DB_READ_HIKARI_MAXIMUM_POOL_SIZE: "10"
  CMP_AMS_DB_READ_HIKARI_MINIMUM_IDLE: "2"
  CMP_AMS_DB_READ_URL: "jdbc:postgresql://pg-dev-pg-db-pgbouncer.postgres-dev.svc.cluster.local:5432/cmp_ams?sslmode=require&connectTimeout=3&socketTimeout=10&options=-c%20client_encoding%3DUTF8"
  CMP_AMS_DB_READ_USER: "cmp"
  CMP_AMS_DB_URL: "jdbc:postgresql://pg-dev-pg-db-pgbouncer.postgres-dev.svc.cluster.local:5432/cmp_ams?sslmode=require&connectTimeout=3&socketTimeout=10&options=-c%20client_encoding%3DUTF8"
  CMP_AMS_DB_USER: "cmp"
  CMP_AMS_INVITE_PUBLIC_BASE_URL: "http://10.0.0.52/ams"
  CMP_AMS_INVITE_REDIS_KEY_PREFIX: "cmp:ams:invite"
  CMP_AMS_RABBIT_BILLING_QUEUE: "cmp.billing.inbound"
  CMP_AMS_REDIS_CONNECT_TIMEOUT: "3s"
  CMP_AMS_REDIS_HOST: "10.0.0.51"
  CMP_AMS_REDIS_PORT: "6379"
  CMP_AMS_REDIS_TIMEOUT: "5s"
  CMP_AMS_TOKEN_ISSUER: "http://10.0.0.52/ams"
  CMP_AMS_TOKEN_JWK_CONNECT_TIMEOUT_MS: "3000"
  CMP_AMS_TOKEN_JWK_READ_TIMEOUT_MS: "5000"
  CMP_AMS_TOKEN_JWK_SET_URI: "http://10.0.0.52/ams/oauth2/jwks"
  CMP_AMS_TOKEN_RSA_PRIVATE_KEY_PATH: "/run/secrets/cmp-ams-rsa.pem"
  CMP_BILLING_AMS_GRPC_ADDRESS: "static://cmp-ams:9090"
  CMP_BILLING_CORS_ALLOW_CREDENTIALS: "true"
  CMP_BILLING_CORS_ALLOWED_HEADERS: "*"
  CMP_BILLING_CORS_ALLOWED_METHODS: "GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD"
  CMP_BILLING_CORS_ALLOWED_ORIGIN_PATTERNS: "*"
  CMP_BILLING_CORS_EXPOSED_HEADERS: "Authorization,Content-Type,X-Request-Id,X-XSRF-TOKEN"
  CMP_BILLING_DB_HIKARI_CONNECTION_TIMEOUT: "3000"
  CMP_BILLING_DB_HIKARI_MAXIMUM_POOL_SIZE: "30"
  CMP_BILLING_DB_HIKARI_MINIMUM_IDLE: "8"
  CMP_BILLING_DB_HIKARI_VALIDATION_TIMEOUT: "1000"
  CMP_BILLING_DB_READ_HIKARI_MAXIMUM_POOL_SIZE: "10"
  CMP_BILLING_DB_READ_HIKARI_MINIMUM_IDLE: "2"
  CMP_BILLING_DB_READ_URL: "jdbc:postgresql://pg-dev-pg-db-pgbouncer.postgres-dev.svc.cluster.local:5432/cmp_billing?sslmode=require&connectTimeout=3&socketTimeout=10&options=-c%20client_encoding%3DUTF8"
  CMP_BILLING_DB_READ_USER: "cmp"
  CMP_BILLING_DB_URL: "jdbc:postgresql://pg-dev-pg-db-pgbouncer.postgres-dev.svc.cluster.local:5432/cmp_billing?sslmode=require&connectTimeout=3&socketTimeout=10&options=-c%20client_encoding%3DUTF8"
  CMP_BILLING_DB_USER: "cmp"
  CMP_BILLING_RABBIT_QUEUE: "cmp.billing.inbound"
  CMP_BILLING_REDIS_CONNECT_TIMEOUT: "3s"
  CMP_BILLING_REDIS_HOST: "10.0.0.51"
  CMP_BILLING_REDIS_PORT: "6379"
  CMP_BILLING_REDIS_TIMEOUT: "5s"
  CMP_IAM_AUDIENCE: "cmp"
  CMP_IAM_CLIENT_ID: "cmp"
  CMP_IAM_HTTP_CONNECT_TIMEOUT_MS: "3000"
  CMP_IAM_HTTP_READ_TIMEOUT_MS: "5000"
  CMP_IAM_ISSUER_URI: "https://iam.vnpost.cloud/realms/vnpost"
  CMP_IAM_JWK_SET_URI: "https://iam.vnpost.cloud/realms/vnpost/protocol/openid-connect/certs"
  CMP_IAM_OIDC_REDIRECT_URI: "http://localhost:3000/ams/api/v1/auth/callback"
  CMP_IAM_POST_LOGIN_REDIRECT_URI: "http://localhost:3000/"
  CMP_IAM_SESSION_COOKIE_SAME_SITE: "Lax"
  CMP_IAM_SESSION_COOKIE_SECURE: "false"
  CMP_RABBIT_HOST: "10.0.0.51"
  CMP_RABBIT_PORT: "5672"
  CMP_RABBIT_USER: "admin"
  CMP_RABBIT_VHOST: "/"
  SERVER_FORWARD_HEADERS_STRATEGY: "framework"
  SPRING_PROFILES_ACTIVE: "prod"

