apiVersion: v1
kind: Secret
metadata:
  name: cmp-backend-secret
  namespace: cmp-backend-dev
type: Opaque
stringData:
  CMP_AMS_DB_PASSWORD: "123zXc_-"
  CMP_AMS_DB_READ_PASSWORD: "123zXc_-"
  CMP_BILLING_DB_PASSWORD: "123zXc_-"
  CMP_BILLING_DB_READ_PASSWORD: "123zXc_-"
  CMP_RABBIT_PASSWORD: "admin123"
  CMP_IAM_CLIENT_SECRET: "DfT0cEpxSn0dXe6YvY5bU99gPe4Bgcvw"
  CMP_AMS_INTERNAL_SECRET: "ISuZTH658fEegC_yV6gVQ4Zrcd2noRcmJTIGp_tQgsU"
  CMP_BILLING_INTERNAL_SECRET: "WDMFnpH92b76OlTpfCLJq4BfHmCCn_voZRjSrf9x0OA"
  cmp-ams-rsa.pem: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCbUHKXnnyPSi76
    1IQF+7K+G9RczVK3tioHRaq+WE/dDFRzB6Y4SouacAcwWzybumGYNDuLk/z53+RO
    rjqsuamN/dwgcfEVy2i0Qk2W2T96ocaiahx/OG3+nBxX9d+fvSWg4dR0NOdPpd2P
    b6oR8AEqvEiQ2kfNCwLrC3pT/MXI/l2sndTFs/cjDSUW5IRdZ2rO76Y5YPMr3btY
    Ail224/o2qRgfmrH5yPgqP7moDUyQ42TRLBKPS4kCY0YhAMqbeL2FQTTfERpCMf9
    EXsdhp8T7sGMPFT8Ue42d9uEBSoUgUx0QDqFy49wtgT7l6epE+dpWHdXXbBc/RhD
    lLTUWIPpAgMBAAECggEAH2L2hWVlzp8zN0VTGNJwoLKHC+oCWVXa0HVnt+eo3Abt
    2gEluiJ2a9NP4JnPebkEl/mWPvK9INH6FVxoRxeOCD/RCE1+ZuUgV60+eMmWZnXi
    6ld/QsZolBeAMtZhRqq2u/hnMsSuKg5e4+mw+McDtVsvXvZ9pBYhlNZQ9kASyDcu
    mhfs+WxrTtjJlcMT/2u+8x2TzRXFMbw4hc7tZF/B/JCeHcIrXHUt9H4GtqhBYqhu
    Swz5fUxDMLr3VOsEN6Pr1FPVHw9nVHZLiLpFeoCGCQHPWgVZqEVjJMaJ1jcIVrX9
    P1hsKwRo50RjeFi0xfaNGER0ChbGYMlhusZauJ0CwQKBgQDOql+XkIR9iJNmewRb
    I+3TdeR7tHVtEQgqccgNjwsPrjSDjxec0edv9POlmko2UTubqgHHTALwLyZdiJeX
    WfiRVN+iBskj0sBvQDQs6n5yTaFP5WUvLFUtymtapi1Og6uWEA9GSwOP5i+nByoe
    E63/BEMsCDzk5PS/OsVbjOdGVQKBgQDAY+yb+TyuqGQWUMl5C7UoV1UaYrcO49Vx
    7tHmVm8wbj8+TrqEsKJVVBaNjU2RL40Rd4prOuNniNUc2n1ypOzwqwjSn3VhnTW2
    ix00b/9F35aoPdQ3QUbVaSfSzyLOiunkrdfQ1CtGrhDyAS6UM65ffMo2YlNt2GAh
    51RiWGFTRQKBgCXHJypBlLaN3MQDAMzYSIU7K8UhO8XwMxnvKq6v00nOgnL6GUrl
    Y/UnRdKj3aUIPGk8Lo8L6g2V0OGQMoXMQI/wf+DSdLpDsEGl7uO3Cd5DKpW8TT7O
    T9PLCMzNS8Lqdtc7oE8tLz2Cynsx6BUPa+MOGGlYKCl/YO4EBEez/iLxAoGAOBNn
    /bZRp57RPWfisXNmJBIAbiZjsOVba0/uwjJjSjx4FpMf7lkFl9VglXWgLDct6O9s
    2wBZE+5gH37XnbjQjv1rHuj3b7JA26oEoyoZv6YB5ZvP5SMToFR8FQfm30jCD7NT
    +jw9OOa3bbJGf0/o/VAEKIHUS2oL6xXgFKIqC/kCgYASUXXAtktLUZh1EcbBRk/v
    TzPNzsmOhL6S5OZoNbp0i1ZVp9v3UATrNkIQXi+jXiLynPSoFCl6jARvWpj1jDnM
    k+oIGHATqkLqaDNR9Ap1VfgmrbHr/fR9LuETID9myn6k7wBjOYv+LW2qn0fVjgkS
    D1SLagNBXW12mD8BwQAVxA==
    -----END PRIVATE KEY-----

