apiVersion: v1
kind: Service
metadata:
  name: valkey-cluster-headless
  namespace: valkey-cluster
spec:
  clusterIP: None
  selector:
    app: valkey-cluster
  ports:
    - name: client
      port: 6379
      targetPort: 6379
    - name: cluster-bus
      port: 16379
      targetPort: 16379