# kubectl -n fleet-local create secret generic gitlab-fleet-cmp-ams-auth  --type=kubernetes.io/basic-auth --from-literal=username='dungct' --from-literal=password='glpat-tZduNPNhsw-fno13lOGIgG86MQp1OjJ2CA.01.0y089lvxt'
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cmp-ams-gitops
  namespace: fleet-local
spec:
  repo: https://scm.vnpost.vn/cloud/cmp/ams.git
  branch: dung-test
  paths:
    - Fleet-ams
  clientSecretName: gitlab-fleet-cmp-ams-auth