# kubectl -n fleet-local create secret generic bms-token  --type=kubernetes.io/basic-auth --from-literal=username='thanhnm1' --from-literal=password='glpat-ut2bBVgaPB281NgV-p5ZWG86MQp1OjNoCA.01.0y1plkq75'
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cmp-bms-gitops
  namespace: fleet-local
spec:
  repo: https://scm.vnpost.vn/cloud/cmp/bms.git
  branch: dev
  paths:
    - fleet
  clientSecretName: bms-token