# kubectl -n fleet-local create secret generic coe-token  --type=kubernetes.io/basic-auth --from-literal=username='thanhnm1' --from-literal=password='glpat-WT4b_EWODwrrWj8jLrqqQ286MQp1OjRwCA.01.0y0pg9vbk'
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cmp-coe-gitops
  namespace: fleet-local
spec:
  repo: https://scm.vnpost.vn/cloud/cmp/coe.git
  branch: deployment/v1.0.0
  paths:
    - fleet
  clientSecretName: coe-token