# kubectl -n fleet-local create secret generic lms-token  --type=kubernetes.io/basic-auth --from-literal=username='thanhnm1' --from-literal=password='glpat-H26AfUYlr7GiQ5crQNZuKW86MQp1OjMzCA.01.0y17ech00'
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cmp-lms-gitops
  namespace: fleet-local
spec:
  repo: https://scm.vnpost.vn/cloud/cmp/lms.git
  branch: dev/cicd
  paths:
    - fleet
  clientSecretName: lms-token