# kubectl -n fleet-local create secret generic pms-token  --type=kubernetes.io/basic-auth --from-literal=username='thanhnm1' --from-literal=password='glpat-VJ8WNYw58FBM4fH2WVAGH286MQp1OjN4CA.01.0y01fd5vb'
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: cmp-pms-gitops
  namespace: fleet-local
spec:
  repo: https://scm.vnpost.vn/cloud/cmp/pms.git
  branch: ops/deployment
  paths:
    - fleet
  clientSecretName: pms-token