---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: m-skwsf-full-access
  namespace: cmp-bms-dev
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: m-skwsf-full-access
  namespace: cmp-bms-dev
subjects:
  - kind: User
    name: m-skwsf
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: m-skwsf-full-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: m-skwsf-full-access
  namespace: cmp-lms-dev
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: m-skwsf-full-access
  namespace: cmp-lms-dev
subjects:
  - kind: User
    name: m-skwsf
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: m-skwsf-full-access
  apiGroup: rbac.authorization.k8s.io
