---
k8s_supported_distributions:
  - Ubuntu

k8s_supported_versions:
  - "22.04"
  - "24.04"

k8s_apt_upgrade_enabled: false

k8s_base_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - conntrack
  - socat
  - ethtool
  - iproute2
  - iptables
  - ebtables
  - kmod
  - vim
  - jq
  - chrony
  - openssh-server
  - helm

k8s_kernel_modules:
  - overlay
  - br_netfilter

k8s_hwe_kernel_enabled: true
k8s_hwe_kernel_reboot: false

k8s_sysctl_params:
  net.ipv4.ip_forward: "1"
  net.bridge.bridge-nf-call-iptables: "1"
  net.bridge.bridge-nf-call-ip6tables: "1"

ssh_hardening_enabled: true
ssh_manage_authorized_keys: true
ssh_user: setup
ssh_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICUcYr1UiNQY2Q5OdVdsHkJM/DkLJWjPxMLLBJu2G/EE cloud@key"
ssh_allow_users:
  - setup
ssh_port: 22
ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_pubkey_authentication: "yes"
ssh_kbd_interactive_authentication: "no"
ssh_challenge_response_authentication: "no"
ssh_x11_forwarding: "no"
ssh_allow_tcp_forwarding: "no"
ssh_client_alive_interval: 300
ssh_client_alive_count_max: 2
ssh_max_auth_tries: 3

chrony_enabled: true
chrony_ntp_servers:
  - "time.google.com"
  - "time.cloudflare.com"
  - "pool.ntp.org"
chrony_timezone: "Asia/Ho_Chi_Minh"

k8s_manage_hosts_file: true
k8s_hosts_entries:
  - ip: "172.23.0.46"
    names:
      - "Kubernetes-worker01"
      - "k8s-wk01"
  - ip: "172.23.0.47"
    names:
      - "Kubernetes-cp01"
      - "k8s-cp01"
  - ip: "172.23.0.48"
    names:
      - "Kubernetes-cp02"
      - "k8s-cp02"
  - ip: "172.23.0.49"
    names:
      - "Kubernetes-worker02"
      - "k8s-wk02"
  - ip: "172.23.0.24"
    names:
      - "Kubernetes-cp03"
      - "k8s-cp03"
  - ip: "172.23.0.28"
    names:
      - "Kubernetes-worker03"
      - "k8s-wk03"

netplan_enabled: true
netplan_apply: false
netplan_renderer: networkd
netplan_config_file: /etc/netplan/01-k8s-static.yaml
netplan_nameservers:
  addresses:
    - "8.8.8.8"
    - "1.1.1.1"
  search:
    - "local"
netplan_mtu: 1500

# RKE2 Air-gap Prepare
rke2_local_images:
  - "../rke2-images/rke2-images.linux-amd64.tar.zst"
rke2_local_binary_bundle: "../rke2-images/rke2.linux-amd64.tar.gz"
rke2_local_install_script: "../rke2-images/install.sh"
rke2_local_checksum: "../rke2-images/sha256sum-amd64.txt"

#Rancher Monitoring Air-gap Prepare
rancher_local_alertmanager_images:
  - "../rancher-images/docker.io_rancher_appco-alertmanager_0.28.1-12.7.tar"
rancher_local_kube_state_metrics_images:
  - "../rancher-images/docker.io_rancher_appco-kube-state-metrics_2.17.0-10.7.tar"
rancher_local_node-exporter_images:
  - "../rancher-images/docker.io_rancher_appco-node-exporter_1.9.1-11.3.tar"
rancher_local_ingress_nginx_images:
  - "../rancher-images/docker.io_rancher_mirrored-ingress-nginx-kube-webhook-certgen_v1.6.2.tar"
rancher_local_prometheus_operator_images:
  - "../rancher-images/docker.io_rancher_mirrored-prometheus-operator-prometheus-operator_v0.85.0.tar"
rancher_local_prometheus_images:
  - "../rancher-images/docker.io_rancher_prom-prometheus_v3.5.0.tar"
rancher_local_grafana_images:
  - "../rancher-images/rancher_appco-grafana_12.1.1-2.2.tar"
rancher_local_sidecar_images:
  - "../rancher-images/rancher_appco-k8s-sidecar_1.30.7-11.3.tar"
rancher_local_kubectl_images:
  - "../rancher-images/rancher_kuberlr-kubectl_v6.0.0.tar"
rancher_local_nginx_images:
  - "../rancher-images/rancher_mirrored-library-nginx_1.29.1-alpine.tar"
rancher_local_prometheus_adapter_images:
  - "../rancher-images/rancher_mirrored-prometheus-adapter-prometheus-adapter_v0.12.0.tar"
rancher_local_chart:
  - "../rancher-images/rancher-monitoring-108.0.1+up77.9.1-rancher.10.tgz"
rancher_local_crds:
  - "../rancher-images/rancher-monitoring-crd-108.0.1+up77.9.1-rancher.10.tgz"
rancher_local_checksum:
  - "../rancher-images/sha256sum-amd64.txt"
rancher_local_values: "../rancher-images/values-airgap.yaml"