apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: valkey
spec:
  serviceName: valkey-headless
  replicas: 3
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: valkey
          image: valkey/valkey:9.1.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - /scripts/start-valkey.sh
          ports:
            - name: valkey
              containerPort: 6379
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: data
              mountPath: /data
            - name: valkey-auth
              mountPath: /etc/valkey-secret
              readOnly: true
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - valkey-cli -a "$(cat /etc/valkey-secret/password)" ping | grep PONG
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - valkey-cli -a "$(cat /etc/valkey-secret/password)" ping | grep PONG
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 512Mi
      volumes:
        - name: scripts
          configMap:
            name: valkey-scripts
            defaultMode: 0755
        - name: valkey-auth
          secret:
            secretName: valkey-auth
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi